Name:           perl-Term-ReadLine-TTYtter
Version:        1.2
Release:        1%{?dist}
Summary:        Term::ReadLine::TTYtter Perl module
License:        Perl (Artistic and GPL)
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Term-ReadLine-TTYtter/
Source0:        http://www.cpan.org/modules/by-module/Term/Term-ReadLine-TTYtter-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(ExtUtils::MakeMaker)
Requires:	perl(Term::ReadKey)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
This is Term::ReadLine::TTYtter. It is a modified version of T::RL::Perl
with several new nonstandard features specific to TTYtter, but may be
useful for other applications:

%prep
%setup -q -n Term-ReadLine-TTYtter-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc CHANGES README
%{perl_vendorlib}/*

%changelog
* Sun Nov 21 2010 Julian C. Dunn <jdunn@aquezada.com> 1.2-1
- Upgrade to 1.2

* Sat Nov 06 2010 Julian C. Dunn <jdunn@aquezada.com> 1.1-1
- Upgrade to 1.1

* Tue Oct 19 2010 Julian C. Dunn <jdunn@aquezada.com> 1.0-1
- Specfile autogenerated by cpanspec 1.78.
